default:
  image: maven-nexus

stages:
  - build
  - test
  - sonarscan
  - deploy

cache:
  - key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - .m2/repository
      - $CI_PROJECT_DIR
      - .sonar/cache

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  GIT_DEPTH: 0
  GIT_CLONE_PATH: $CI_BUILDS_DIR/Si-MA
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache

build:
  stage: build
  artifacts:
    paths:
      - "target"
  script:
    - mvn install -DskipTests
  when: always
  only:
    - pushes
    - merge_requests

test:
  stage: test
  artifacts:
    paths:
      - "target"
  script:
    - mvn test
  when: always
  only:
    - pushes
    - merge_requests

sonarqube-check:
  stage: sonarscan
  artifacts:
    paths:
      - "target"
  script:
    - mvn clean install verify sonar:sonar
  allow_failure: true
  only:
    - pushes
    - merge_requests

deploy:
  stage: deploy
  artifacts:
    paths:
      - "target/*.jar"
  script:
    - mvn deploy clean -Dmaven.test.skip=true
  only:
    - master
    - tags