default:
  image: maven:3.8.2-openjdk-16

stages:
  - build
  - test-and-scan
  - deploy-artifact

cache:
  - key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - .m2/repository
      - $CI_PROJECT_DIR
      - .sonar/cache

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "-s .m2/settings.xml"
  GIT_DEPTH: 0
  GIT_CLONE_PATH: $CI_BUILDS_DIR/Si-MA
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache

compile-job:
  stage: build
  artifacts:
    paths:
      - "target"
  script:
    - mvn $MAVEN_CLI_OPTS -Dmaven.test.skip=true install
  when: always
  only:
    - pushes
    - merge_requests

test-job:
  stage: test-and-scan
  needs: [ "compile-job" ]
  artifacts:
    paths:
      - "target"
  script:
    - mvn $MAVEN_CLI_OPTS test
  when: on_success
  only:
    - pushes
    - merge_requests

sonarqube-check:
  stage: test-and-scan
  needs: [ "compile-job" ]
  artifacts:
    paths:
      - "target"
  script:
    - mvn $MAVEN_CLI_OPTS clean install verify sonar:sonar
  allow_failure: true
  when: on_success
  only:
    - merge_requests
    - master

deploy-artifact-job:
  stage: deploy-artifact
  needs: [ "compile-job", "test-job" ]
  artifacts:
    paths:
      - "target/*.jar"
  script:
    - mvn $MAVEN_CLI_OPTS -Dmaven.test.skip=true deploy clean
  only:
    refs:
      - merge_requests
    changes:
      - pom.xml
  when: manual