name: Maven Nexus Sonatype publication

on:
  release:
    types: [created]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.15
        uses: actions/setup-java@v1
        with:
          java-version: 1.15

      - name: Generate settings.xml for Maven Builds
        uses: whelk-io/maven-settings-xml-action@v12
        with:
          servers: '[{"id": "nexus-snapshots", "username": "admin", "password": "CallimardAdmine94500$"}]'

      - name: Deploy on Nexus Sonatype
        run: mvn deploy clean -Dmaven.test.skip=true